var annotated_dup =
[
    [ "Aula", "class_aula.html", "class_aula" ],
    [ "AulaAcompanhada", "class_aula_acompanhada.html", "class_aula_acompanhada" ],
    [ "AulaAcompanhadaMesmoTempoException", "class_aula_acompanhada_mesmo_tempo_exception.html", "class_aula_acompanhada_mesmo_tempo_exception" ],
    [ "AulaLivre", "class_aula_livre.html", "class_aula_livre" ],
    [ "ConfirmException", "class_confirm_exception.html", "class_confirm_exception" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "DataFormatoException", "class_data_formato_exception.html", "class_data_formato_exception" ],
    [ "DiaSemanaException", "class_dia_semana_exception.html", "class_dia_semana_exception" ],
    [ "EmptyStringException", "class_empty_string_exception.html", "class_empty_string_exception" ],
    [ "Horario", "class_horario.html", "class_horario" ],
    [ "HorarioNotExistsException", "class_horario_not_exists_exception.html", "class_horario_not_exists_exception" ],
    [ "HorarioPiscinaException", "class_horario_piscina_exception.html", "class_horario_piscina_exception" ],
    [ "IdentificacaoAulaNotExitentException", "class_identificacao_aula_not_exitent_exception.html", "class_identificacao_aula_not_exitent_exception" ],
    [ "IdNotExistentException", "class_id_not_existent_exception.html", "class_id_not_existent_exception" ],
    [ "InBoundsException", "class_in_bounds_exception.html", "class_in_bounds_exception" ],
    [ "InsertVectorException", "class_insert_vector_exception.html", "class_insert_vector_exception" ],
    [ "InsuficientUsersException", "class_insuficient_users_exception.html", "class_insuficient_users_exception" ],
    [ "InvalidDataException", "class_invalid_data_exception.html", "class_invalid_data_exception" ],
    [ "IsNotNumberException", "class_is_not_number_exception.html", "class_is_not_number_exception" ],
    [ "IsStringNumberException", "class_is_string_number_exception.html", "class_is_string_number_exception" ],
    [ "LimitAulaLivreTimeException", "class_limit_aula_livre_time_exception.html", "class_limit_aula_livre_time_exception" ],
    [ "LimitTimeException", "class_limit_time_exception.html", "class_limit_time_exception" ],
    [ "MaxUtentesException", "class_max_utentes_exception.html", "class_max_utentes_exception" ],
    [ "Pessoa", "class_pessoa.html", "class_pessoa" ],
    [ "Piscina", "class_piscina.html", "class_piscina" ],
    [ "Professor", "class_professor.html", "class_professor" ],
    [ "ProfessoresDisponiveisException", "class_professores_disponiveis_exception.html", "class_professores_disponiveis_exception" ],
    [ "SaldoInsuficienteException", "class_saldo_insuficiente_exception.html", "class_saldo_insuficiente_exception" ],
    [ "TriesException", "class_tries_exception.html", "class_tries_exception" ],
    [ "Utente", "class_utente.html", "class_utente" ]
];